Renamed `group` to `auth_group`
avantifellows/db-service pull request #158
Opened 2024-03-16 16:15 UTC by sudheshna-donthineni

2024-03-19 08:50 UTC, suryabulusu commented on lib/dbservice/enrollment_record/enrollment_record.ex
> +    if get_field(changeset, :start_end, :end_date) != nil do
start_date

2024-03-19 08:50 UTC, suryabulusu commented on lib/dbservice/enrollment_record/enrollment_record.ex
> +      validate_start_end_datetime(changeset, :start_end, :end_date)
start_date

2024-03-19 08:55 UTC, suryabulusu commented on lib/dbservice/sessions/session.ex
> +    field(:signup_form, :boolean)
why is activate signup removed

2024-03-19 08:57 UTC, suryabulusu commented on lib/dbservice/sessions/session.ex
> +      :session_id,
i dont think session_id should be part of. validation.. when we create sessions on session-creator, initially there is no session id. later on, a lambda function creates session id and updates db rows

2024-03-19 09:03 UTC, suryabulusu commented on lib/dbservice_web/controllers/group_controller.ex
> +  @spec index(Plug.Conn.t(), any) :: Plug.Conn.t()
whats this line 😨

2024-03-19 09:08 UTC, suryabulusu reviewed
left comments

2024-03-19 09:41 UTC, Bahugunajii requested changes

2024-03-19 09:41 UTC, Bahugunajii commented on lib/dbservice/batches/batch.ex
> +      where: [group_type: "batch"]
Why we still have `group_type` here?

2024-03-19 09:41 UTC, Bahugunajii commented on lib/dbservice/batch_programs.ex
Any reason of removing it?

2024-03-19 09:41 UTC, Bahugunajii commented on lib/dbservice/enrollment_record/enrollment_record.ex
> +  alias Dbservice.Users.User
I think an `enrollment_record` should be of a `student` and not the `user`. What is the reason of associating it with user?

2024-03-19 09:41 UTC, Bahugunajii commented on lib/dbservice/schools/school.ex
> +      :af_school_categorycategory,
```suggestion
      :af_school_category,
```

2024-03-21 05:48 UTC, Bahugunajii requested changes
How a `product` can be created?

2024-03-21 17:35 UTC, Bahugunajii approved these changes

2024-03-22 05:19 UTC, merged