Removes current batch/grade/group
avantifellows/db-service pull request #172
Opened 2024-05-15 13:53 UTC by suryabulusu

Redundant info in user profile

2024-05-19 17:06 UTC, Bahugunajii requested changes

2024-05-19 17:06 UTC, Bahugunajii commented on mix.lock
Let's not add `mix.lock` file as it may throw version compatibility errors while deployment

2024-07-04 05:12 UTC, pritamps approved these changes
Looks good!

2024-08-23 06:23 UTC, pritamps approved these changes

2025-06-18 06:40 UTC, Bahugunajii approved these changes

2025-06-18 06:40 UTC, merged